#define ADC_ADDRESS         0b1100101
#define IO_EXPANDER_ADDRESS 0b0100111

#define IO_EXPANDER_IODIR_A 0x00
#define IO_EXPANDER_IODIR_B 0x01
#define IO_EXPANDER_OLAT_A  0x14
#define IO_EXPANDER_OLAT_B  0x15

#define I2C_TIMEOUT 50

#define NO_OF_CHANNELS 10

#define VREF 3.3
#define ADC_BITU_SKAICIUS 8
#define ADC_VERCIU_KIEKIS (1<<ADC_BITU_SKAICIUS)

#define V_STEP VREF/(ADC_VERCIU_KIEKIS)/STIPRINIMAS
#define ALARM_RAW_DATA_THRESHOLD (int)(ALARM_VOLTAGE_THRESHOLD/(VREF/STIPRINIMAS)*ADC_VERCIU_KIEKIS) //Padarome floor operacija)

#define ALARM_VOLTAGE_THRESHOLD 0.05
#define STIPRINIMAS 60



////////////////////////////////////////////


#define TIMER_LAIKAS 250